unit MP4AutoAtom;

interface

uses
  System.SysUtils, System.Types, System.UITypes, System.Classes, System.Variants,
  Generics.Defaults, Generics.Collections, MP4Atoms, MP4DerivedAtoms, MP4Types;

function CreateAutoAtom(FStream: TStream; const AtomRec: TAtomRec): TAtom;

implementation

function CreateAutoAtom(FStream: TStream; const AtomRec: TAtomRec): TAtom;
begin
  case AtomRec.FourCC of
    { Binary Blob Atom }
    $6D646174: // mdat
      Result := TAtomOpaqueData.Create(AtomRec);

    { Empty Atoms }
    $66726565: // free
      Result := TAtomFree.Create(AtomRec);
    $736B6970: // skip
      Result := TAtomSkip.Create(AtomRec);
    $77696465: // wide
      Result := TAtomWide.Create(AtomRec);

    { Container Atoms }
    $65647473: // edts
      Result := TAtomContainer.Create(AtomRec);
    $6D646961: // mdia
      Result := TAtomContainer.Create(AtomRec);
    $6D696E66: // minf
      Result := TAtomContainer.Create(AtomRec);
    $6D6F6F76: // moov
      Result := TAtomContainer.Create(AtomRec);
    $7374626C: // stbl
      Result := TAtomContainer.Create(AtomRec);
    $7472616B: // trak
      Result := TAtomContainer.Create(AtomRec);
    $74726566: // tref
      Result := TAtomContainer.Create(AtomRec);
    $75647461: // udta
      Result := TAtomContainer.Create(AtomRec);

    { Full Container Atoms }
    $6D657461: // meta
      Result := TAtomMeta.Create(FStream, AtomRec);

    { AutoGenerated Data Atoms }
    $66747970: // ftyp
      Result := TAtomFtyp.Create(FStream, AtomRec);
    $6D766864: // mvhd
      Result := TAtomMvhd.Create(FStream, AtomRec);
    $746B6864: // tkhd
      Result := TAtomTkhd.Create(FStream, AtomRec);
    $696C7374: // ilst
      Result := TAtomIlst.Create(FStream, AtomRec);
    $6368706C: // chpl
      Result := TAtomChpl.Create(FStream, AtomRec);
    $63686170: // chap
      Result := TAtomChap.Create(FStream, AtomRec);
    $656C7374: // elst
      Result := TAtomElst.Create(FStream, AtomRec);

  else
    Result := Nil;
  end;
end;

end.
